### PR TITLE
Changes to sign in UI. Changes to what data is stored in firebase

### PR DESCRIPTION
**Pull request by btorogers**
I tried pulling Petar's changes but firebase stopped working properly, I assume it was changes to google-services.json. So copied his changes into my last commit to make sure all worked and made some additional changes on top of that

### CODE REVIEW

**Comment by btorogers** [comment]
I suggest you just overwrite the conflicting files. I know its not great practice but probably easiest in this case, if that's something you have the option to do I'm not really sure

**Comment by marc-st** [comment]
Yeah no problem..

I've just went through and resolved the conflicts with the master branch. Let me know if there are any issues because I haven't got round to testing it.

**Comment by btorogers** [comment]
No that didn't work, reintroduced the same merge issues. I think it'd be best if you just cloned my repository and used git push -f. I've rolled mine back to how it was before the merge

**Comment by marc-st** [comment]
What exactly was the merge issue? What about if you try sending a pull request from your working repository. Then we can see where this issue is.

**Comment by marc-st** [comment]
some errors were created in PR #4 . for some reason not all the files were updated. nevertheless I have now updated this branch manually to the latest version. so pull from this and test it works on your side.

**Pull request merged**
